"""Shared constants for the reusable animated-thumbnail modules."""

from __future__ import annotations

ADDON_ID = "blender_animated_ui"
CACHE_SCHEMA_VERSION = 1
SAMPLE_PLAN_VERSION = 1

IMAGEIO_FFMPEG_REQUIREMENT = "imageio-ffmpeg==0.6.0"

MAX_SAMPLED_FRAMES = 60
TARGET_FRAME_MS = 100
DEFAULT_STATIC_FRAME_MS = 1000
MAX_THUMBNAIL_EDGE = 512

PREVIEW_TIMER_INTERVAL_SECONDS = 0.05
PREVIEW_MIN_REDRAW_INTERVAL_SECONDS = 0.03
PREVIEW_PLAYBACK_PAUSE_INTERVAL_SECONDS = 0.5
PREVIEW_INTERACTION_THROTTLE_SECONDS = 0.35
PREVIEW_INTERACTION_PAUSE_INTERVAL_SECONDS = 0.4
PREVIEW_FRAME_CHANGE_THROTTLE_SECONDS = 0.2
PREVIEW_HEALTH_CHECK_INTERVAL_SECONDS = 1.0
PREVIEW_STALE_HEARTBEAT_SECONDS = 3.0
PREVIEW_UI_TARGET_STALE_SECONDS = 3.0

GALLERY_PAGE_SIZE = 12
GALLERY_BASE_TILE_WIDTH_PX = 92.0
GALLERY_ICON_SCALE = 5.0
