"""Shared constants for the reusable animated-thumbnail modules."""

from __future__ import annotations

ADDON_ID = "blender_animated_ui"
CACHE_SCHEMA_VERSION = 1
SAMPLE_PLAN_VERSION = 1

IMAGEIO_FFMPEG_REQUIREMENT = "imageio-ffmpeg==0.6.0"

CACHE_FRAME_WARNING_THRESHOLD = 1200
DEFAULT_IMPORT_FPS = 22
DEFAULT_PREVIEW_FPS = 10
MIN_PREVIEW_FPS = 8
MAX_PREVIEW_FPS = 60
DEFAULT_STATIC_FRAME_MS = 1000
MAX_THUMBNAIL_EDGE = 192

PREVIEW_TIMER_INTERVAL_SECONDS = 0.05
PREVIEW_MIN_REDRAW_INTERVAL_SECONDS = 1.0 / MAX_PREVIEW_FPS
PREVIEW_PLAYBACK_PAUSE_INTERVAL_SECONDS = 0.5
PREVIEW_INTERACTION_THROTTLE_SECONDS = 0.35
PREVIEW_INTERACTION_PAUSE_INTERVAL_SECONDS = 0.4
PREVIEW_FRAME_CHANGE_THROTTLE_SECONDS = 0.2
PREVIEW_HEALTH_CHECK_INTERVAL_SECONDS = 1.0
PREVIEW_STALE_HEARTBEAT_SECONDS = 3.0
PREVIEW_UI_TARGET_STALE_SECONDS = 3.0
PREVIEW_LOAD_BATCH_INTERVAL_SECONDS = 0.1
PREVIEW_LOAD_BATCH_SIZE = 8
PREVIEW_OFFSCREEN_GRACE_SECONDS = 5.0
PREVIEW_LOOKAHEAD_FRAMES = 2

GALLERY_PAGE_SIZE = 12
GALLERY_BASE_TILE_WIDTH_PX = 92.0
GALLERY_ICON_SCALE = 5.0
